### ISSUE TITLE
Hard to tell if it's working as intended.

### ISSUE THREAD

**Issue by elvey** [aokellermann/nexus-now#5]
I almost filed a bug entitled _Doesn't work (in Brave). Add support?_ 

I thought it wasn't working.  It was, just not on all DOIs. 

So the lack of an error message and of a message as suggested in the P.S. at the end is the issue.  

Original Issue description:  (title: _Doesn't work (in Brave). Add support?_ )
Is there anything we need to configure before it'll work?  I try it and it opens up a save file dialog box, and (for example) creates a 10.1056 subdirectory, but no file is actually downloaded. It opens up https://libstc.cc/#/nexus_science/id.dois:10.1056/NEJMp2402379, but again, no file is actually downloaded. I have opted in to autodownload.
Version 0.2.3 in Brave on MacOS on ARM.

P.S.:  It would be helpful if to have a DOI that is known to work in the README.  Not sure what DOI would serve well.

**Comment by aokellermann** [comment]
This extension opens up STC web if autodownload fails because sometimes STC web provides a fallback method of getting the PDF. The problem with providing a known DOI that works is that sometimes the Nexus developers do maintenance and everything breaks. In your case, the article is simply too new so it hasn't been uploaded to Nexus yet.
